#!/usr/bin/env bash

# Print which RTS options are available.
# stack exec $program_name -- +RTS -?

# See https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/profiling.html#profiling
# Run the program with
# -p: profiling support
# -S: additional statistics
# -h: memory heap profile
# -H: set heap size
# -K: set stack size
# -l: event log (compile option is necessary)

source include

msg "EvoMode-Seq profiling run."
file_profile="${project_root}/data/Profile.fa.gz"
stack exec seq-ana --work-dir $prof_dir -- \
      summarize -a DNAIUPAC "$file_profile" \
      +RTS -p -l -s || exit 1
      # +RTS -p -hy -l -s || exit 1

msg "EvoMode-Sim profiling run."
file_tree="${project_root}/data/Newick.tree"
file_edm="${project_root}/data/EDMDistsPhylobayes.txt"
stack exec seq-sim --work-dir $prof_dir -- \
      -t "$file_tree" -o seq-sim.out -e "$file_edm" -m "EDM[LG-Custom]" -l 5000 -s [0] \
      +RTS -p -hc -l -s || exit 1

msg "Create graphs of the memory heap profiles."
for f in *.hp
do
    hp2ps -e10in -c "$f"
done
