#!/usr/bin/env bash

source include

pr="$project_root"

cd "${pr}" || exit 1

while IFS= read -r -d '' file
do
    stylish-haskell -i "$file"
done < <(find "${pr}/src"/ "${pr}/test"/ "${pr}/app/" -name '*.hs' -print0)
