#!/usr/bin/env bash

prog_name=evolution-modify

file_DNA=test/Data/Nucleotide.fasta
file_AA=test/Data/AminoAcid.fasta

stack build || exit 1
stack exec $prog_name -- -a DNA $file_DNA || exit 1
stack exec $prog_name -- -a Protein $file_AA || exit 1
