* Reproducible evolution made easy

The ELynx suite is a Haskell library and a tool set for computational biology.

- [[file:slynx/README.org][SLynx]] :: Examine, modify, and simulate evolutionary sequences (FASTA format).
- [[file:evomod-tree/README.org][TLynx]] :: Analyze, and simulate phylogenetic trees (Newick format).
     
* Installation

ELynx is written in [[https://www.haskell.org/][Haskell]] and can be installed with [[https://docs.haskellstack.org/en/stable/README/][Stack]].

1. Install Stack with your package manager, or directly from the web
   page.

   #+BEGIN_EXAMPLE
       curl -sSL https://get.haskellstack.org/ | sh
   #+END_EXAMPLE

2. Clone the ELynx repository.

   #+BEGIN_EXAMPLE
       git clone clone https://github.com/dschrempf/elynx
   #+END_EXAMPLE

3. Navigate to the newly created =elynx= folder and build the binaries.
   This will take a while.

   #+BEGIN_EXAMPLE
       stack build
   #+END_EXAMPLE

4. Run a binary from within the project directory. For example,

   #+BEGIN_EXAMPLE
       stack exec tlynx -- --help
   #+END_EXAMPLE

5. If needed, install the binaries.

   #+BEGIN_EXAMPLE
       stack install
   #+END_EXAMPLE

   The binaries are installed into =~/.local/bin/= which has to be added [[https://en.wikipedia.org/wiki/PATH_(variable)][PATH]].
   Then, they can be used directly.

