* Reproducible evolution made easy

The EvoMod suite is a Haskell library and a tool set for computational biology.

- [[file:evomod-seq/README.org][Sequence analysis]] :: View, examine, and modify evolutionary sequences (FASTA
     format) with =seq-ana=.
- [[file:evomod-seq/README.org][Sequence simulation]] :: Simulate evolutionary sequences (FASTA format)with
     =seq-sim=.
- [[file:evomod-tree/README.org][Tree simulation]] :: Simulate phylogenetic trees (Newick format) with
     =tree-sim=.
     
* Installation

EvoMod is written in [[https://www.haskell.org/][Haskell]] and can be
installed with
[[https://docs.haskellstack.org/en/stable/README/][Stack]].

1. Install Stack with your package manager, or directly from the web
   page.

   #+BEGIN_EXAMPLE
       curl -sSL https://get.haskellstack.org/ | sh
   #+END_EXAMPLE

2. Clone the EvoMod repository.

   #+BEGIN_EXAMPLE
       git clone clone https://github.com/dschrempf/evomod
   #+END_EXAMPLE

3. Navigate to the newly created =evomod= folder and build the binaries.
   This will take a while.

   #+BEGIN_EXAMPLE
       stack build
   #+END_EXAMPLE

4. Run a binary from within the project directory. For example,

   #+BEGIN_EXAMPLE
       stack exec tree-sim -- --help
   #+END_EXAMPLE

5. If needed, install the binaries.

   #+BEGIN_EXAMPLE
       stack install
   #+END_EXAMPLE

   The binaries are installed into =~/.local/bin/= which has to be added
   [[https://en.wikipedia.org/wiki/PATH_(variable)][PATH]]. Now, the
   binary can be directly used.

