resolver: lts-18.3

packages:
  - elynx
  - elynx-markov
  - elynx-nexus
  - elynx-seq
  - elynx-tools
  - elynx-tree
  - slynx
  - tlynx

# ghc-options:
#   # Optimizations.
#   "$everything": -fllvm -O2
#   # # Profiling.
#   # "$locals": -eventlog
#   # Weeder 2.0.
#   "$locals": -fwrite-ide-info

# Nix integration via shell because the unfree mkl library is used.
nix:
  add-gc-roots: true
  path: [nixpkgs=/home/dominik/Nix/Nixpkgs]
  shell-file: shell.nix
