resolver: nightly-2021-09-17

packages:
  - elynx
  - elynx-markov
  - elynx-nexus
  - elynx-seq
  - elynx-tools
  - elynx-tree
  - slynx
  - tlynx

# ghc-options:
#   # Optimizations.
#   "$everything": -fllvm -O2
#   # # Profiling.
#   # "$locals": -eventlog
#   # Weeder 2.0.
#   "$locals": -fwrite-ide-info
