* Notes
** Read from standard input
I decided to not provide an option for reading from STDIN, since this is a
corner case and additionally because behavior might be undefined when more than
one input file is given. When does one file end and the next one begin?

** Automatic code detection
I decided that there should not be any automatic code detection. Reaons:
1. Reproducible runs.
2. Separation between extended and IUPAC codes.

* Easy
Provide descriptions (or headers?) for all sub commands so that they show up in
help.

* Medium
** TODO Improve output of (mixture, gamma) model

** TODO Enable description in FASTA files sequence headers

** TODO Provide a (Args a) type
** TODO Abstract data types
- Do not export value constructors for important central data types.

* Hard
** TODO ELynx file
Provide an internal =OutFileBaseName.elynx= file that stores all input files and
commands so that the exact run can be replicated from this elynx file.

* Requires further tought
** TODO Reduce complexity of tree data types
