#!/usr/bin/env bash

prog_name=evomod-seq

file_DNA=../evomod-lib/test/Data/Nucleotide.fasta
file_AA=../evomod-lib/test/Data/AminoAcid.fasta

stack build || exit 1

stack exec $prog_name -- summarize -a DNA $file_DNA || exit 1
stack exec $prog_name -- summarize -a Protein $file_AA || exit 1

echo Test if EvoMod is quiet.
stack exec $prog_name -- summarize -a DNA -q $file_DNA || exit 1
