#!/usr/bin/env bash

source include

# flags=("--fast")

# if [[ $1 == "prod" ]]; then
#     msg "Set flags for production build."
#     flags=()
# fi

flags=()

msg "Normal build with documentation."
stack build "${flags[@]}" --haddock || exit 1

msg "Profile build."
stack build "${flags[@]}" --profile --work-dir .stack-work-profiling || exit 1

msg "EvoMod test suite."
stack build "${flags[@]}" --test --work-dir .stack-work-testing || exit 1
