#!/usr/bin/env bash

normal_build() {
    source include
    msg "Normal build with documentation."
    stack build "${flags[@]}" --haddock || exit 1
}
# export -f normal_build

profile_build() {
    source include
    msg "Profile build."
    stack build "${flags[@]}" --profile --work-dir .stack-work-profiling || exit 1
}
# export -f profile_build

test_build() {
    source include
    msg "EvoMod test suite."
    stack build "${flags[@]}" --test --work-dir .stack-work-testing || exit 1
}
# export -f test_build

flags=(--fast)
if [[ $1 == "prod" ]]
then
    flags=()
elif [[ $1 == "test" ]]
then
    test_build
    exit 0
fi

normal_build
profile_build
test_build

# Run the build in parallel but output is not colored.
# parallel {} ::: normal_build profile_build test_build || exit 1


