#!/usr/bin/env bash

source include

normal_build() {
    msg "Normal build with documentation."
    msg "Flags: ${flags[*]}"
    stack build "${flags[@]}" || exit 1
}

profile_build() {
    msg "Profile build."
    msg "Flags: ${flags[*]}"
    stack build "${flags[@]}" --profile --work-dir "$prof_dir" || exit 1
}

test_build() {
    msg "Test suite."
    msg "Flags: ${flags[*]}"
    stack build "${flags[@]}" --test --work-dir "$test_dir" || exit 1
}

if [[ $2 == "clean" ]]
then
    stack clean --full
fi

if [[ -z $1 ]]
then
    echo "Usage: ./build (fast|prod|prof|test)"
    exit 1
elif [[ $1 == "fast" ]]
then
    flags=(--fast)
    normal_build
elif [[ $1 == "prod" ]]
then
    flags=(--haddock --test)
    normal_build
elif [[ $1 == "prof" ]]
then
    flags=()
    profile_build
elif [[ $1 == "test" ]]
then
    flags=(--fast)
    test_build
fi
