#!/usr/bin/env bash

set -e

source include

usage() {
    echo "Usage: $(basename "$0") [MAJOR|major|minor|reset Ma ma mi]"
    echo ""
    echo "When resetting the version, provide space separated"
    echo "MAJOR, major, and minor version numbers."
    echo "For example,"
    echo "$(basename "$0") reset 0 0 1"
}

increment() {
    echo "$1" 1 | awk '{printf "%d", $1 + $2}'
}

assert_integer() {
    re='^[0-9]+$'
    if ! [[ $1 =~ $re ]] ; then
        echo "error: Not a number" >&2; exit 1
    fi
}

# Also removes whitespace.
version_old=$(xargs < "${project_root}/version")
version_MAJOR="${version_old%%.*}"
version_major_tmp="${version_old#*.}"
version_major="${version_major_tmp%.*}"
version_minor="${version_old##*.}"

if [[ $1 == "MAJOR" ]]
then
    version_MAJOR=$(increment "$version_MAJOR")
    version_major="0"
    version_minor="0"
elif [[ $1 == "major" ]]
then
    version_major=$(increment "$version_major")
    version_minor="0"
elif [[ $1 == "minor" ]]
then
    version_minor=$(increment "$version_minor")
elif [[ $1 == "reset" ]]
then
    if [[ $# != 4 ]]
    then
        usage
        exit 1
    else
        assert_integer "$2"
        assert_integer "$3"
        assert_integer "$4"
        version_MAJOR=$2
        version_major=$3
        version_minor=$4
    fi
else
    usage
    exit 1
fi
version_new="${version_MAJOR}.${version_major}.${version_minor}"
version_new_list="[${version_MAJOR}, ${version_major}, ${version_minor}]"

echo "Bump $1 version number."
echo "Version old: $version_old"
echo "Version new: $version_new"

echo "$version_new" > "${project_root}/version"

fd '.*package.yaml' "${project_root}" -x \
   sed -i -r '/^version:\s+/s/[0-9]+\.[0-9]+\.[0-9]+/'"${version_new}"'/'

fd 'README.org' "${project_root}" -x \
   sed -i -r '/^Version:\s+/s/[0-9]+\.[0-9]+\.[0-9]+/'"${version_new}"'/'

# Replace version in ELynx.Tools.Definitions
sed -i -r '/^version = makeVersion\s+/s/\[[0-9]+, [0-9]+, [0-9]+/'"${version_new_list}"'/'

echo "Done."
