#!/usr/bin/env bash

source include

./build fast || exit 1

file_tree=../data/Newick.tree

if [[ $1 == "s" ]]
then
    msg "EvoMod-Sim; substitution model."
    stack exec evomod-sim -- \
          -t $file_tree -o evomod-sim.out -m "HKY[6.0]{0.2,0.3,0.3,0.2}" -l 10000 -s [0] || exit 1
elif [[ $1 == "e" ]]
then
    msg "EvoMod-Sim; empirical distribution mixture model."
    file_edm=../data/EDMDistsPhylobayes.txt
    stack exec evomod-sim -- \
          -t $file_tree -o evomod-sim.out -e $file_edm -m "EDM[LG-Custom]" -l 10000 -s [0] || exit 1
else
    msg "Usage: ./evomod-sim (s|e)"
    exit 1
fi

