#!/usr/bin/env bash

source include

msg "Seq-Ana help text."
stack exec seq-ana -- --help || exit 1

msg "Seq-Ana version text."
stack exec seq-ana -- --version || exit 1

msg "Seq-Sim help text."
stack exec seq-sim -- --help || exit 1

msg "Seq-Sim version text."
stack exec seq-sim -- --version || exit 1
