#!/usr/bin/env bash

source include

if [[ -z $1 ]]
then
    echo "Usage: $0 filename"
    exit 1
fi

edm_file="${project_root}/data/EDMDistsIQTREE.nex"
tree_file="${project_root}/data/Newick.tree"

iqtree -nt 4 -s "$1" -pre iqtree-verify -mdef "$edm_file" -m LG+CF004ModelOpt

if hash newick-compare 2>/dev/null
then
    newick-compare iqtree-verify.treefile "$tree_file"
else
    echo "Trees have to be compared manually."
fi

echo "Estimated weights have to be compared manually."
