#!/usr/bin/env bash

source include

dot_file_bn="${project_root}/scripts/module-dependencies"

for module in "${modules[@]}"
do
    cd "$module" || exit 1
    module_bn=$(basename "$module")
    graphmod -q -r Main \
             . > "${dot_file_bn}-${module_bn}.dot" || exit 1
done

echo "Draw and analyze graphs with 'xdot'."
