#!/usr/bin/env bash

# TODO.
echo TODO. This has to be changed because packages have been split up!
exit 0

# source include

# cd "${project_root}" || exit 1

# dot_file="${project_root}/scripts/module-dependencies.dot"

# graphmod -q \
#          -r Main \
#          -r ParseModuleString \
#          -r EvoMod.ArgParse \
#          -R EvoMod.Tools \
#          -r EvoMod.Definitions \
#          . > "$dot_file" \
#     || exit 1

# xdot "$dot_file"
