#!/usr/bin/env bash

# Print which RTS options are available.
# stack exec $program_name -- +RTS -?

# See https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/profiling.html#profiling
# Run the program with
# -p: profiling support
# -S: additional statistics
# -h: memory heap profile
# -H: set heap size
# -K: set stack size
# -l: event log (compile option is necessary)

set -e

source include

seq-ana() {
    msg "Seq-Ana profiling run."
    file_profile="${project_root}/evomod-seq/data/Profile.fa.gz"
    stack exec --work-dir $prof_dir --profile seq-ana -- \
          -a ProteinI examine "$file_profile" \
          +RTS -p -l -s || exit 1
}

seq-sim() {
    msg "Seq-Sim profiling run."
    file_tree="${project_root}/evolib-tree/data/Newick.tree"
    file_edm="${project_root}/evolib-seq/data/EDMDistsPhylobayes.txt"
    stack  exec --work-dir $prof_dir --profile seq-sim  -- \
          -t "$file_tree" -o seq-sim.out -e "$file_edm" -m "EDM(LG-Custom)" -l 5000 -S [0] \
          +RTS -p -hc -l -s || exit 1
}

tree-sim() {
    msg "Tree-Sim profiling run."
    stack exec --work-dir $prof_dir --profile tree-sim -- \
          -t 10 -n 3000 -r 0.5 -u -o tree-sim.out -S [0] \
          +RTS -p -hc -l -s || exit 1
}

graph() {
    msg "Create graphs of the memory heap profiles."
    for f in *.hp
    do
        hp2ps -e10in -c "$f"
    done
}

if [[ $1 == "seq-ana" ]]
then
    seq-ana
elif [[ $1 == "seq-sim" ]]
then
    seq-sim
elif [[ $1 == "tree-sim" ]]
then
    tree-sim
else
    echo "Usage: $(basename "$0") (seqana|seqsim|treesim)"
    exit 1
fi

graph
