#!/usr/bin/env bash

set -e

source include

file_DNA="${project_root}/elynx-seq/data/Nucleotide.fasta"
file_AA="${project_root}/elynx-seq/data/AminoAcid.fasta"

msg "Seq-Ana; examine DNA."
stack exec seq-ana -- -a DNA examine "$file_DNA" || exit 1

msg "Seq-Ana; examine protein data."
stack exec seq-ana -- -a Protein examine "$file_AA" || exit 1

msg "Seq-Ana; concatenate DNA."
stack exec seq-ana -- -a DNA concatenate "$file_DNA" "$file_DNA" || exit 1

msg "Seq-Ana; examine; test if quiet."
stack exec seq-ana -- -a DNA -v Quiet examine "$file_DNA" || exit 1

