#!/usr/bin/env bash

set -e

source include

project_root=$(stack path | grep "project-root" | tr -s " " | cut -d " " -f 2)
file_DNA="${project_root}/elynx-seq/data/Nucleotide.fasta"
file_AA="${project_root}/elynx-seq/data/AminoAcid.fasta"
file_tree="${project_root}/elynx-tree/data/Newick.tree"
file_edm="${project_root}/elynx-markov/data/EDMDistsPhylobayes.txt"
file_siteprofiles="${project_root}/elynx-markov/data/HSSPMany.siteprofiles"

msg "SLynx; examine DNA."
cabal exec slynx -- examine -a DNA "$file_DNA"

msg "SLynx; examine protein data."
cabal exec slynx -- examine -a Protein "$file_AA"

msg "SLynx; concatenate DNA."
cabal exec slynx -- concatenate -a DNA "$file_DNA" "$file_DNA"

msg "SLynx; examine; test if quiet."
cabal exec slynx -- -v Quiet examine -a DNA "$file_DNA"

msg "SLynx; simulate; substitution model."
cabal exec slynx -- simulate -t "$file_tree" -s "HKY[6.0]{0.2,0.3,0.3,0.2}" -l 1000 -S [0]

msg "SLynx; GTR4 model."
cabal exec slynx -- simulate -t "$file_tree" -s "GTR4[1,2,3,4,5,6]{0.2,0.3,0.4,0.1}" -l 1000 -S [0]

msg "SLynx; simulate; empirical distribution mixture model."
cabal exec slynx -- simulate -t "$file_tree" -e "$file_edm" -m "EDM(LG-Custom)" -l 1000 -S [0]

msg "SLynx; empirical distribution mixture model with custom weights."
cabal exec slynx -- simulate -t "$file_tree" -e "$file_edm" -m "EDM(LG-Custom)" -w "[0.9,0.05,0.03,0.02]" -l 1000 -S [0]

msg "SLynx; CXX distribution mixture model."
cabal exec slynx -- simulate -t "$file_tree" -m "C20" -l 1000 -S [0]

msg "SLynx; gamma rate heterogeneity."
cabal exec slynx -- simulate -t "$file_tree" -g "(4,0.2)" -s "HKY[6.0]{0.2,0.3,0.3,0.2}" -l 1000 -S [0]

msg "SLynx; CXX distribution mixture model with gamma rate heterogeneity."
cabal exec slynx -- simulate -t "$file_tree" -m "C10" -g "(4,0.2)" -l 1000 -S [0]

msg "SLynx; standard mixture model."
cabal exec slynx -- simulate -t "$file_tree" -m "MIXTURE(JC,HKY[6.0]{0.25,0.25,0.25,0.25})" -w "[0.4,0.6]" -l 1000 -S [0]

msg "SLynx; site profile EDM model."
cabal exec slynx -- simulate -t "$file_tree" -m "EDM(Poisson-Custom)" -p "$file_siteprofiles" -l 1000 -S [0]
