#!/usr/bin/env bash

prog_name=evomod

stack build || exit 1

echo EvoMod help text.
echo --
stack exec $prog_name -- --help || exit 1

echo
echo EvoMod version text.
echo --
stack exec $prog_name -- --version || exit 1

